import Head from "next/head";
import Section1 from "../components/Home/section1";
import Section2 from "../components/Home/section2";
import Section3 from "../components/Home/section3";
import Layout from "../components/Layout";

export default function HomePage() {
  return (
    <>
      <Head>
        <title>Meliorit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icons/favicon.png" />
      </Head>
      <Layout>
        <Section1 />
        <Section2 />
        <Section3 />
      </Layout>
    </>
  );
}
